name: Data Scrape
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 4" # At 05:00 UTC every Thursday
jobs:
  data-scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: npm install
      - name: Scrape Data
        run: npm run scrape
      - name: Report Data
        run: npm run report
      - name: Commit
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git pull
          git add .
          git commit -m "Data Scrape"
          git push